HTML/CSS & JavaScript capstone project - Conference page
AlselwiAisha/Capstone-project pull request #10
Opened 2023-05-31 10:39 UTC by AlselwiAisha

- Build home page and about page.
- Have versions for 2 different screen sizes: Mobile and Desktop.
- The home page has a link in the menu to the about page.
- The logo in the header links to the home page.
- Added mobile menu.
- Sectors and members sections created dynamically in JavaScript.

2023-05-31 11:55 UTC, levy002 requested changes
## Hello @AlselwiAisha   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make sure to wrap your top navigation bar into the `nav` tag which will increase the page accessibility. Please remember to edit both files `index.html` and `about.html`.
       
       
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/a50c31fd-6340-4a06-bc6c-7090cc52748e)

- [x] Kindly make sure to align the `footer` contents in the center of the page in order to match the provided Behance design.

   - ### YOUR DESIGN
   
  ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/fda340df-f9aa-4608-80c3-912f98191072)

   - ### BEHANCE DESIGN
   
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/2a91093f-ff12-452d-93cd-b8b903888a43)

 - [x] Kindly make sure to remove the Partners and Footer section on the mobile version on the Home page. The Behance doesn't show those two sections in the Home page mobile version. Kindly fix that.
  
 - ### YOUR DESIGN
 
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/36d9d547-4d0d-432f-80a7-5f1e4c86de35)

 - ### BEHANCE DESIGN
 
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/66913b7d-f0d6-4bd6-839c-3c7fd6551f8b)


- [ ] Kindly make sure to use the provided Google font `Lato` and `COCOGOOSE`. In order to use this special font you have to import them from [google fonts](https://fonts.google.com/) and then have access to it in order to use it in your project. Kindly make sure your website's typography matches the provided one on Behance design by using the correct font.


- [ ] Kindly make sure to add the red short line which locates under each section title in order to match the provided Behance design as much as possible.

  - ### YOUR DESIGN
  
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/606aeb8f-a102-4245-8ebd-3bd5ed63a9a6)

   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/efbbb7b0-eb05-41b4-a97b-23c0b1defd99)

    ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/59d490dd-91ae-43cf-9b4d-14480f251d5c)

  - ### BEHANCE DESIGN
  
     ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/45330bd1-2c99-4537-819c-a560f90cd9d7)

   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/c31f49a8-82ff-4903-b5eb-88525f86d033)

   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/cc4f4d5b-473a-4527-970c-3d94b655dcc0)


- [ ] Kindly make sure the working title of all speakers is written in the same font style as the Behance design show.

  - ### YOUR DESIGN
  
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/a2ebf973-e0d1-4f2f-8c33-eb40af28368f)


  - ### BEHANCE DESIGN
  
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/107448f0-eba1-4e18-afa5-fbc565a39316)


- [ ] Kindly make sure to remove all comments and placeholder text in your README file in order to keep your repository clean and professional.

  
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/e078dcf0-d402-4a1b-8d35-7f464a3c8404)


 - [ ] Kindly make sure to adjust the border of your button in order to match the provided design as much as possible. 

   - ### YOUR DESIGN
   
   ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/6a581d0b-8c74-425b-b62b-fae2e101dccd)

   - ### BEHANCE DESIGN
   
    ![image](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/cb89b010-3f16-49c1-9f63-11e759efb019)

- [ ] Kindly make sure the paragraphs of the sectors card are aligned on the same straight vertical line in order to match the provided Behance design. 
- [ ] Kindly make sure the typography of the sectors card contents matches the one on the provided Behance design.

  - ### YOUR DESIGN
  
  ![chrome-capture-2023-4-31](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/35a42659-d943-4d21-b78a-1c91262a27bc)

  - ### BEHANCE DESIGN
  
    ![chrome-capture-2023-4-31 (1)](https://github.com/AlselwiAisha/Capstone-project/assets/87197412/ae6749f2-96da-4e3e-b462-6e2862a5122f)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 16:26 UTC, usorfaitheloho requested changes
> Hi @AlselwiAisha  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Awesome design✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 16:26 UTC, usorfaitheloho commented on index.html
>  </html>
As suggested by the previous reviewer, please remove all commented lines of code and descriptions from your README file in order to have a clean and legible code 😄

2023-05-31 16:35 UTC, AlselwiAisha commented on index.html
>  </html>
Sorry, I don't get the issue.

2023-06-01 05:04 UTC, levy002 approved these changes
## Hello @AlselwiAisha 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 05:59 UTC, merged